cookie_array = []
wasted_cookie = []
ip = "0.0.0.0"
port = 8484
check_update = false
auto_update = false
no_fs = false
log_to_file = false
password = "sk-ponsde"
admin_password = "sk-ponsde"
max_retries = 5
preserve_chats = false
web_search = false
enable_web_count_tokens = false
sanitize_messages = false
skip_first_warning = false
skip_second_warning = false
skip_restricted = false
skip_non_pro = false
skip_rate_limit = true
skip_normal_pro = false
use_real_roles = true
custom_prompt = ""
